### ISSUE TITLE
Aguardando Código

### ISSUE THREAD

**Issue by Marii-brito** [PetJournal/petjournal.api#11]
Definição:

Como usuário, quero poder digitar o código de verificação para recuperar minha senha.

Descrição:

Nessa tela o objetivo é que o usuário consiga recuperar a senha caso ele tenha perdido ou esquecido. E para isso ele deverá passar por três processos: enviar o código de recuperação para o email ou telefone, digitar o código recebido e criar uma senha nova. Se esses três passos forem feitos, o usuário poderá ter acesso ao aplicativo novamente.

[Protótipo Figma - Aguardando Código](https://www.figma.com/proto/ynvraEWObyi5rxueisWlPs/Telas-Pet-Journal?node-id=586-996&scaling=min-zoom&page-id=564%3A835&starting-point-node-id=586%3A996url)

![Image](https://user-images.githubusercontent.com/129445779/232586830-440f4603-b978-4953-8374-207c7a24a67a.png)

Critérios de Aceite:

> O código de verificação deve conter 6 dígitos numéricos. 

> Quando` o usuário digitar o código de verificação corretamente o botão “Enviar” deverá ser habilitado, ao clicar no botão o mesmo deve ser redirecionado para tela onde poderá criar a nova senha.

> Caso o usuário selecione a opção “reenviar código", ele será redirecionado para tela onde é possível adicionar o emailpara receber o novo código de verificação.

> Se o sistema, após o clique em “Enviar” verificar que o código de verificação esteja incorreto, uma mensagem de aviso deve ser apresentada na tela: 

`“O código de verificação que você inseriu não é válido. Verifique o código e tente novamente”.`

> Se o sistema, após o clique em “Enviar” verificar que o código de verificação esteja correto, o usuário deverá ser redirecionado para tela “[Troque a Senha](https://docs.google.com/document/d/1aqk79LZt29eRKpKNySt-zJNhHLJzKLJz/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)”.

> Associações:

[Troque a Senha](https://docs.google.com/document/d/1aqk79LZt29eRKpKNySt-zJNhHLJzKLJz/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)

**Comment by dansenpir** [comment]
@rodrigofmeneses se atente quando for iniciar essa task, pois ela depende do JWT que foi iniciado na task #2 do @maztt.
